name: Clear All Caches
on: workflow_dispatch

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache list -R ${{ github.repository }} --limit 100 --json id -q '.[].id' | xargs -I {} gh cache delete {} -R ${{ github.repository }}
